### ISSUE TITLE
How to transcribe claims

### ISSUE THREAD

**Issue by PieterKas** [arndt-s/ietf-identity-chaining#10]
What guidance should be given on transcribing claims (e.g. how should they be namespaced? Is there something we can borrow from OpenID Connect)?

**Comment by arndt-s** [comment]
Keeping it open to add reference to transaction token draft

**Comment by arndt-s** [comment]
Discussed offline, we'll leave claim transcription out of scope but will also mention this at IETF 118 in Prague
