### ISSUE TITLE
Review use cases

### ISSUE THREAD

**Issue by PieterKas** [arndt-s/ietf-identity-chaining#12]
Review use cases to make sure they reflect the needs accurately and that the proposed solution works for all the proposed use cases.

**Comment by PieterKas** [comment]
Consider collapsing into a single use case to reduce cognitive load/manage expectations.

**Comment by PieterKas** [comment]
As discussed with Kelly and Arndt, we will use a single use case (2.1.3 only)

**Comment by arndt-s** [comment]
Resolved with #23
