### ISSUE TITLE
RS A always sends token exchange request

### ISSUE THREAD

**Issue by kburgin3** [arndt-s/ietf-identity-chaining#51]
In the "Authorization sever acting as a client" section, suggest having RS A make a token exchange request to AS A instead of a regular token request.

**Comment by PieterKas** [comment]
@kburgin3 can you create a PR or this issue?

**Comment by arndt-s** [comment]
Discussed with Pieter, will update flow and rename step A to `request or exchange token ..` - in the description RFC8693 is linked.
